### ISSUE TITLE
Support specifying a gap between highlight and tooltip

### ISSUE THREAD

**Issue by glasheen99** [pseudoankit/coachmark#17]
I use tooltips without arrows, so I like to display a small gap between the highlight and the tooltip.  I currently realize this gap via padding around the tooltip composable, in all four directions.  But this approach will be wasteful in cases where the tooltip is sized not to run off the left or right side of the screen.  I could switch on position to put the padding only on the side that needs it (adjacent to the highlight), but a centralized solution might be better, in case other users need the same thing.

The gap could be specified on UnifyCoachmark, and defaulted to 0.dp for backward compatibility.

**Comment by glasheen99** [comment]
I can do this on my fork and then create a PR, if you give me the green light.  It'll probably be a couple days before I start on it.

**Comment by ankitk77** [comment]
sure will do this

**Comment by ankitk77** [comment]
Hey @glasheen99 , I checked this
Since Tooltip is configurable client side so let client do it
adding a extra param would not be a big change but with library evolving params will keep on increasing and hence it may create confustion for end users
Since user knows in which direction we are putting tooltip, so they can adjust padding direction accordingly
What do you say ?

**Comment by glasheen99** [comment]
It would have been useful for me, and perhaps other users eventually (to save having to "reinvent the wheel" on tooltips without arrows), but I'm trying a different approach now.
